### PR TITLE
James1

### PR DESCRIPTION
**Pull request by jlucassen**
Renamed textattack to eukaryote, so we can work on it without name conflicting with the actual textattack module
Added t4a folder inside eukaryote, which contains tats4aardvarks code
Attempted to structure tats4aardvarks code as a proper submodule and also clean it up a little
Also includes a little improvised list of tests I was running manually

### CODE REVIEW

**Review by dhpitt — CHANGES_REQUESTED** [review]
changes

**Review by kjohnson3595 — COMMENTED** [review]
Here's a review

**Review by nanakonoda — APPROVED** [review]
This is a comment

**Review by nanakonoda — APPROVED** [review]
This is a comment

**Review by nanakonoda — APPROVED** [review]
This is a comment

**Review by ansiiww — APPROVED** [review]
tests action passed

**Review by kjohnson3595 — APPROVED** [review]
skimmed

**Pull request merged**
